eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8085/eureka
    instance:
        prefer-ip-address: true
server:
    port: 9090
spring:
    application:
        name: Daksh
